# Generated by GEMINI 2026-08-31


# ==============================================================================
# 1. LOCAL LOGIC & FLATTENING (Provider Toggles & Safe Loop Handling)
# ==============================================================================
locals {
  # Conditional checks to determine which providers are enabled
  deploy_aws          = contains(var.dns_providers, "aws")
  deploy_digitalocean = contains(var.dns_providers, "digitalocean")
  deploy_dnsimple     = contains(var.dns_providers, "dnsimple")

  # Flatten the nested MX records structure cleanly so it never errors out if empty
  mx_flattened = flatten([
    for record_key, mx_list in var.mx_records : [
      for item in mx_list : {
        key      = record_key
        priority = item.priority
        value    = item.value
      }
    ]
  ])
}

# ==============================================================================
# 2. AWS ROUTE 53 RESOURCES
# ==============================================================================
resource "aws_route53_zone" "primary" {
  count = local.deploy_aws ? 1 : 0
  name  = var.domain_name
}

resource "aws_route53_record" "a" {
  for_each = local.deploy_aws ? var.a_records : {}

  zone_id = aws_route53_zone.primary[0].zone_id
  name    = each.key == "@" ? var.domain_name : "${each.key}.${var.domain_name}"
  type    = "A"
  ttl     = 300
  records = [each.value]
}

resource "aws_route53_record" "cname" {
  for_each = local.deploy_aws ? var.cname_records : {}

  zone_id = aws_route53_zone.primary[0].zone_id
  name    = "${each.key}.${var.domain_name}"
  type    = "CNAME"
  ttl     = 300
  records = [each.value]
}

resource "aws_route53_record" "txt" {
  for_each = local.deploy_aws ? var.txt_records : {}

  zone_id = aws_route53_zone.primary[0].zone_id
  name    = each.key == "@" ? var.domain_name : "${each.key}.${var.domain_name}"
  type    = "TXT"
  ttl     = 300
  records = [each.value]
}

resource "aws_route53_record" "mx" {
  # Safe unique keys created using string combinations from the flattened list
  for_each = local.deploy_aws ? { for idx, record in local.mx_flattened : "${record.key}_${idx}" => record } : {}

  zone_id = aws_route53_zone.primary[0].zone_id
  name    = each.value.key == "@" ? var.domain_name : "${each.value.key}.${var.domain_name}"
  type    = "MX"
  ttl     = 300
  records = ["${each.value.priority} ${each.value.value}"]
}

# ==============================================================================
# 3. DIGITALOCEAN RESOURCES
# ==============================================================================
# resource "digitalocean_domain" "default" {
#   count = local.deploy_digitalocean ? 1 : 0
#   name  = var.domain_name
# }
#
# resource "digitalocean_record" "a" {
#   for_each = local.deploy_digitalocean ? var.a_records : {}
#
#   domain = digitalocean_domain.default[0].id
#   type   = "A"
#   name   = each.key
#   value  = each.value
#   ttl    = 300
# }
#
# resource "digitalocean_record" "cname" {
#   for_each = local.deploy_digitalocean ? var.cname_records : {}
#
#   domain = digitalocean_domain.default[0].id
#   type   = "CNAME"
#   name   = each.key
#   value  = "${each.value}." # DigitalOcean handles fully-qualified target values natively
#   ttl    = 300
# }
#
# resource "digitalocean_record" "txt" {
#   for_each = local.deploy_digitalocean ? var.txt_records : {}
#
#   domain = digitalocean_domain.default[0].id
#   type   = "TXT"
#   name   = each.key
#   value  = each.value
#   ttl    = 300
# }
#
# resource "digitalocean_record" "mx" {
#   for_each = local.digitalocean ? { for idx, record in local.mx_flattened : "${record.key}_${idx}" => record } : {}
#
#   domain   = digitalocean_domain.default[0].id
#   type     = "MX"
#   name     = each.value.key
#   priority = each.value.priority
#   value    = "${each.value.value}."
#   ttl      = 300
# }

# ==============================================================================
# 4. DNSIMPLE RESOURCES
# ==============================================================================
# resource "dnsimple_zone_record" "a" {
#   for_each = local.deploy_dnsimple ? var.a_records : {}
#
#   zone_name  = var.domain_name
#   type       = "A"
#   name       = each.key == "@" ? "" : each.key
#   value      = each.value
#   ttl        = 300
# }
#
# resource "dnsimple_zone_record" "cname" {
#   for_each = local.deploy_dnsimple ? var.cname_records : {}
#
#   zone_name  = var.domain_name
#   type       = "CNAME"
#   name       = each.key
#   value      = each.value
#   ttl        = 300
# }
#
# resource "dnsimple_zone_record" "txt" {
#   for_each = local.deploy_dnsimple ? var.txt_records : {}
#
#   zone_name  = var.domain_name
#   type       = "TXT"
#   name       = each.key == "@" ? "" : each.key
#   value      = each.value
#   ttl        = 300
# }
#
# resource "dnsimple_zone_record" "mx" {
#   for_each = local.deploy_dnsimple ? { for idx, record in local.mx_flattened : "${record.key}_${idx}" => record } : {}
#
#   zone_name  = var.domain_name
#   type       = "MX"
#   name       = each.value.key == "@" ? "" : each.value.key
#   priority   = each.value.priority
#   value      = each.value.value
#   ttl        = 300
# }
